/**
 * UFLI Lesson Configs — Lessons 1–34
 *
 * Complete configuration for all UFLI Foundations lessons.
 * Words automatically classified as core (high-frequency AAC) or fringe (topic-specific).
 * Review words track which lesson introduced each word.
 * Heart words are irregular, high-frequency words introduced this lesson.
 * Morphology notes capture tense variations and other phonetic features.
 *
 * Core words based on: Banajee et al., 2003; Van Tatenhove, 2009; AAC research standards
 * Fringe words: less frequent, topic-specific words from UFLI lessons
 */

const lessons = [

  {
    number: 1,
    phoneme: '/ă/',
    grapheme: 'a',
    newWords: [
    ],
    reviewWords: [
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 2,
    phoneme: '/m/',
    grapheme: 'm',
    newWords: [
    ],
    reviewWords: [
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 3,
    phoneme: '/s/',
    grapheme: 's',
    newWords: [
    ],
    reviewWords: [
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 4,
    phoneme: '/t/',
    grapheme: 't',
    newWords: [
    ],
    reviewWords: [
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 5,
    phoneme: '',
    grapheme: 'VC & CVC',
    newWords: [
      { word: 'at', type: 'core' },
      { word: 'mat', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'at', from: 'Lesson 5', type: 'core' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 6,
    phoneme: '/p/',
    grapheme: 'p',
    newWords: [
      { word: 'ap', type: 'fringe' },
      { word: 'at', type: 'core' },
      { word: 'map', type: 'fringe' },
      { word: 'mat', type: 'fringe' },
      { word: 'pat', type: 'fringe' },
      { word: 'sap', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ap', from: 'Lesson 6', type: 'fringe' },
      { word: 'at', from: 'Lesson 5', type: 'core' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'sap', from: 'Lesson 6', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'tat', from: 'Lesson 5', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 7,
    phoneme: '/f/',
    grapheme: 'f',
    newWords: [
      { word: 'fat', type: 'fringe' },
      { word: 'map', type: 'fringe' },
      { word: 'sap', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'fat', from: 'Lesson 7', type: 'fringe' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'sap', from: 'Lesson 6', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'tat', from: 'Lesson 6', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 8,
    phoneme: '/ĭ/',
    grapheme: 'i',
    newWords: [
      { word: 'fit', type: 'fringe' },
      { word: 'if', type: 'core' },
      { word: 'it', type: 'core' },
      { word: 'pim', type: 'fringe' },
      { word: 'pit', type: 'fringe' },
      { word: 'sip', type: 'fringe' },
      { word: 'sit', type: 'fringe' },
      { word: 'Tim', type: 'fringe' },
      { word: 'tip', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'fat', from: 'Lesson 7', type: 'fringe' },
      { word: 'fit', from: 'Lesson 8', type: 'fringe' },
      { word: 'if', from: 'Lesson 8', type: 'core' },
      { word: 'it', from: 'Lesson 8', type: 'core' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pim', from: 'Lesson 8', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'sap', from: 'Lesson 6', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'sip', from: 'Lesson 8', type: 'fringe' },
      { word: 'sit', from: 'Lesson 8', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'Tim', from: 'Lesson 8', type: 'fringe' },
      { word: 'tip', from: 'Lesson 8', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 9,
    phoneme: '/n/',
    grapheme: 'n',
    newWords: [
      { word: 'fin', type: 'fringe' },
      { word: 'fit', type: 'fringe' },
      { word: 'in', type: 'core' },
      { word: 'it', type: 'core' },
      { word: 'map', type: 'fringe' },
      { word: 'nap', type: 'fringe' },
      { word: 'nip', type: 'fringe' },
      { word: 'pin', type: 'fringe' },
      { word: 'pit', type: 'fringe' },
      { word: 'sap', type: 'fringe' },
      { word: 'sip', type: 'fringe' },
      { word: 'sit', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'tin', type: 'fringe' },
      { word: 'tip', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'fit', from: 'Lesson 8', type: 'fringe' },
      { word: 'if', from: 'Lesson 8', type: 'core' },
      { word: 'in', from: 'Lesson 9', type: 'core' },
      { word: 'it', from: 'Lesson 8', type: 'core' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'nap', from: 'Lesson 9', type: 'fringe' },
      { word: 'nip', from: 'Lesson 9', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pin', from: 'Lesson 9', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'sap', from: 'Lesson 6', type: 'fringe' },
      { word: 'sip', from: 'Lesson 8', type: 'fringe' },
      { word: 'sit', from: 'Lesson 8', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
      { word: 'tip', from: 'Lesson 8', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 10,
    phoneme: '',
    grapheme: 'CVC',
    newWords: [
      { word: 'at', type: 'core' },
      { word: 'fat', type: 'fringe' },
      { word: 'fin', type: 'fringe' },
      { word: 'fit', type: 'fringe' },
      { word: 'if', type: 'core' },
      { word: 'in', type: 'core' },
      { word: 'it', type: 'core' },
      { word: 'map', type: 'fringe' },
      { word: 'mat', type: 'fringe' },
      { word: 'pat', type: 'fringe' },
      { word: 'pin', type: 'fringe' },
      { word: 'pit', type: 'fringe' },
      { word: 'sap', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
      { word: 'sit', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'tin', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'at', from: 'Lesson 5', type: 'core' },
      { word: 'fat', from: 'Lesson 7', type: 'fringe' },
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'fit', from: 'Lesson 8', type: 'fringe' },
      { word: 'if', from: 'Lesson 8', type: 'core' },
      { word: 'in', from: 'Lesson 9', type: 'core' },
      { word: 'it', from: 'Lesson 8', type: 'core' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'nap', from: 'Lesson 9', type: 'fringe' },
      { word: 'nat', from: 'Lesson 9', type: 'fringe' },
      { word: 'nip', from: 'Lesson 9', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pin', from: 'Lesson 9', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'sap', from: 'Lesson 6', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'sip', from: 'Lesson 8', type: 'fringe' },
      { word: 'sit', from: 'Lesson 8', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
      { word: 'tip', from: 'Lesson 8', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
      { word: 'letter', base: 'sound', note: 'variant of "sound"' },
    ],
  },

  {
    number: 11,
    phoneme: '',
    grapheme: 'Nasalized A',
    newWords: [
      { word: 'am', type: 'core' },
      { word: 'an', type: 'core' },
      { word: 'at', type: 'core' },
      { word: 'Fan', type: 'fringe' },
      { word: 'man', type: 'fringe' },
      { word: 'Pam', type: 'fringe' },
      { word: 'pan', type: 'fringe' },
      { word: 'pat', type: 'fringe' },
      { word: 'Sam', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
      { word: 'Tam', type: 'fringe' },
      { word: 'tan', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'am', from: 'Lesson 11', type: 'core' },
      { word: 'an', from: 'Lesson 11', type: 'core' },
      { word: 'at', from: 'Lesson 5', type: 'core' },
      { word: 'fan', from: 'Lesson 11', type: 'fringe' },
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'fit', from: 'Lesson 8', type: 'fringe' },
      { word: 'if', from: 'Lesson 8', type: 'core' },
      { word: 'in', from: 'Lesson 9', type: 'core' },
      { word: 'it', from: 'Lesson 8', type: 'core' },
      { word: 'man', from: 'Lesson 11', type: 'fringe' },
      { word: 'nap', from: 'Lesson 9', type: 'fringe' },
      { word: 'nip', from: 'Lesson 9', type: 'fringe' },
      { word: 'Pam', from: 'Lesson 11', type: 'fringe' },
      { word: 'pan', from: 'Lesson 11', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'Sam', from: 'Lesson 11', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'sip', from: 'Lesson 8', type: 'fringe' },
      { word: 'Tam', from: 'Lesson 11', type: 'fringe' },
      { word: 'tan', from: 'Lesson 11', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'tat', from: 'Lesson 10', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
      { word: 'tip', from: 'Lesson 8', type: 'fringe' },
    ],
    heartWords: ["an"],
    morphologyNotes: [
      { word: 'an', base: 'Am', note: 'variant of "Am"' },
    ],
  },

  {
    number: 12,
    phoneme: '/ŏ/',
    grapheme: 'o',
    newWords: [
      { word: 'fat', type: 'fringe' },
      { word: 'map', type: 'fringe' },
      { word: 'mat', type: 'fringe' },
      { word: 'mop', type: 'fringe' },
      { word: 'nop', type: 'fringe' },
      { word: 'not', type: 'core' },
      { word: 'on', type: 'core' },
      { word: 'op', type: 'fringe' },
      { word: 'pat', type: 'fringe' },
      { word: 'pop', type: 'fringe' },
      { word: 'pot', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'top', type: 'fringe' },
      { word: 'tot', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'am', from: 'Lesson 11', type: 'core' },
      { word: 'an', from: 'Lesson 11', type: 'core' },
      { word: 'fam', from: 'Lesson 11', type: 'fringe' },
      { word: 'fan', from: 'Lesson 11', type: 'fringe' },
      { word: 'fat', from: 'Lesson 7', type: 'fringe' },
      { word: 'man', from: 'Lesson 11', type: 'fringe' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'mop', from: 'Lesson 12', type: 'fringe' },
      { word: 'nan', from: 'Lesson 11', type: 'fringe' },
      { word: 'nop', from: 'Lesson 12', type: 'fringe' },
      { word: 'not', from: 'Lesson 12', type: 'core' },
      { word: 'on', from: 'Lesson 12', type: 'core' },
      { word: 'op', from: 'Lesson 12', type: 'fringe' },
      { word: 'pam', from: 'Lesson 11', type: 'fringe' },
      { word: 'pan', from: 'Lesson 11', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pin', from: 'Lesson 9', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'pop', from: 'Lesson 12', type: 'fringe' },
      { word: 'pot', from: 'Lesson 12', type: 'fringe' },
      { word: 'sam', from: 'Lesson 11', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'tan', from: 'Lesson 11', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'top', from: 'Lesson 12', type: 'fringe' },
      { word: 'tot', from: 'Lesson 12', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 13,
    phoneme: '/d/',
    grapheme: 'd',
    newWords: [
      { word: 'ad', type: 'fringe' },
      { word: 'dot', type: 'fringe' },
      { word: 'fad', type: 'fringe' },
      { word: 'mad', type: 'fringe' },
      { word: 'mod', type: 'fringe' },
      { word: 'nod', type: 'fringe' },
      { word: 'not', type: 'core' },
      { word: 'pad', type: 'fringe' },
      { word: 'pod', type: 'fringe' },
      { word: 'pot', type: 'fringe' },
      { word: 'sad', type: 'fringe' },
      { word: 'sod', type: 'fringe' },
      { word: 'tad', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ad', from: 'Lesson 13', type: 'fringe' },
      { word: 'dot', from: 'Lesson 13', type: 'fringe' },
      { word: 'fad', from: 'Lesson 13', type: 'fringe' },
      { word: 'fan', from: 'Lesson 11', type: 'fringe' },
      { word: 'mad', from: 'Lesson 13', type: 'fringe' },
      { word: 'man', from: 'Lesson 11', type: 'fringe' },
      { word: 'mod', from: 'Lesson 13', type: 'fringe' },
      { word: 'mom', from: 'Lesson 12', type: 'fringe' },
      { word: 'mop', from: 'Lesson 12', type: 'fringe' },
      { word: 'nod', from: 'Lesson 13', type: 'fringe' },
      { word: 'not', from: 'Lesson 12', type: 'core' },
      { word: 'pad', from: 'Lesson 13', type: 'fringe' },
      { word: 'pam', from: 'Lesson 11', type: 'fringe' },
      { word: 'pan', from: 'Lesson 11', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'pod', from: 'Lesson 13', type: 'fringe' },
      { word: 'pom', from: 'Lesson 12', type: 'fringe' },
      { word: 'pop', from: 'Lesson 12', type: 'fringe' },
      { word: 'pot', from: 'Lesson 12', type: 'fringe' },
      { word: 'sad', from: 'Lesson 13', type: 'fringe' },
      { word: 'sod', from: 'Lesson 13', type: 'fringe' },
      { word: 'sop', from: 'Lesson 12', type: 'fringe' },
      { word: 'tad', from: 'Lesson 13', type: 'fringe' },
      { word: 'tom', from: 'Lesson 12', type: 'fringe' },
      { word: 'top', from: 'Lesson 12', type: 'fringe' },
      { word: 'tot', from: 'Lesson 12', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 14,
    phoneme: '/k/',
    grapheme: 'c',
    newWords: [
      { word: 'cam', type: 'fringe' },
      { word: 'can', type: 'core' },
      { word: 'cap', type: 'fringe' },
      { word: 'cat', type: 'fringe' },
      { word: 'cod', type: 'fringe' },
      { word: 'con', type: 'fringe' },
      { word: 'cop', type: 'fringe' },
      { word: 'cot', type: 'fringe' },
      { word: 'map', type: 'fringe' },
      { word: 'mat', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ad', from: 'Lesson 13', type: 'fringe' },
      { word: 'am', from: 'Lesson 11', type: 'core' },
      { word: 'an', from: 'Lesson 11', type: 'core' },
      { word: 'cam', from: 'Lesson 14', type: 'fringe' },
      { word: 'can', from: 'Lesson 14', type: 'core' },
      { word: 'cap', from: 'Lesson 14', type: 'fringe' },
      { word: 'cat', from: 'Lesson 14', type: 'fringe' },
      { word: 'cod', from: 'Lesson 14', type: 'fringe' },
      { word: 'con', from: 'Lesson 14', type: 'fringe' },
      { word: 'cop', from: 'Lesson 14', type: 'fringe' },
      { word: 'cot', from: 'Lesson 14', type: 'fringe' },
      { word: 'dad', from: 'Lesson 13', type: 'fringe' },
      { word: 'dan', from: 'Lesson 13', type: 'fringe' },
      { word: 'did', from: 'Lesson 13', type: 'core' },
      { word: 'dim', from: 'Lesson 13', type: 'fringe' },
      { word: 'din', from: 'Lesson 19', type: 'fringe' },
      { word: 'dip', from: 'Lesson 13', type: 'fringe' },
      { word: 'mad', from: 'Lesson 13', type: 'fringe' },
      { word: 'man', from: 'Lesson 11', type: 'fringe' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'mod', from: 'Lesson 13', type: 'fringe' },
      { word: 'nod', from: 'Lesson 13', type: 'fringe' },
      { word: 'sad', from: 'Lesson 13', type: 'fringe' },
      { word: 'sod', from: 'Lesson 13', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 15,
    phoneme: '/ŭ/',
    grapheme: 'u',
    newWords: [
      { word: 'cup', type: 'fringe' },
      { word: 'cut', type: 'fringe' },
      { word: 'dun', type: 'fringe' },
      { word: 'fun', type: 'fringe' },
      { word: 'not', type: 'core' },
      { word: 'nut', type: 'fringe' },
      { word: 'pin', type: 'fringe' },
      { word: 'pit', type: 'fringe' },
      { word: 'pot', type: 'fringe' },
      { word: 'pun', type: 'fringe' },
      { word: 'sum', type: 'fringe' },
      { word: 'sun', type: 'fringe' },
      { word: 'un', type: 'fringe' },
      { word: 'up', type: 'core' },
      { word: 'us', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'cam', from: 'Lesson 14', type: 'fringe' },
      { word: 'can', from: 'Lesson 14', type: 'core' },
      { word: 'cap', from: 'Lesson 14', type: 'fringe' },
      { word: 'cat', from: 'Lesson 14', type: 'fringe' },
      { word: 'cod', from: 'Lesson 14', type: 'fringe' },
      { word: 'con', from: 'Lesson 14', type: 'fringe' },
      { word: 'cop', from: 'Lesson 14', type: 'fringe' },
      { word: 'cot', from: 'Lesson 14', type: 'fringe' },
      { word: 'cup', from: 'Lesson 15', type: 'fringe' },
      { word: 'cut', from: 'Lesson 15', type: 'fringe' },
      { word: 'dun', from: 'Lesson 15', type: 'fringe' },
      { word: 'fun', from: 'Lesson 15', type: 'fringe' },
      { word: 'not', from: 'Lesson 12', type: 'core' },
      { word: 'nut', from: 'Lesson 15', type: 'fringe' },
      { word: 'pin', from: 'Lesson 9', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'pot', from: 'Lesson 12', type: 'fringe' },
      { word: 'pun', from: 'Lesson 15', type: 'fringe' },
      { word: 'sam', from: 'Lesson 11', type: 'fringe' },
      { word: 'sim', from: 'Lesson 14', type: 'fringe' },
      { word: 'sum', from: 'Lesson 15', type: 'fringe' },
      { word: 'sun', from: 'Lesson 15', type: 'fringe' },
      { word: 'tam', from: 'Lesson 11', type: 'fringe' },
      { word: 'tim', from: 'Lesson 8', type: 'fringe' },
      { word: 'tom', from: 'Lesson 14', type: 'fringe' },
      { word: 'top', from: 'Lesson 12', type: 'fringe' },
      { word: 'un', from: 'Lesson 15', type: 'fringe' },
      { word: 'up', from: 'Lesson 15', type: 'core' },
      { word: 'us', from: 'Lesson 15', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 16,
    phoneme: '/g/',
    grapheme: 'g',
    newWords: [
      { word: 'cot', type: 'fringe' },
      { word: 'cut', type: 'fringe' },
      { word: 'dig', type: 'fringe' },
      { word: 'dog', type: 'fringe' },
      { word: 'dot', type: 'fringe' },
      { word: 'dug', type: 'fringe' },
      { word: 'fig', type: 'fringe' },
      { word: 'gap', type: 'fringe' },
      { word: 'gas', type: 'fringe' },
      { word: 'got', type: 'core' },
      { word: 'gum', type: 'fringe' },
      { word: 'gut', type: 'fringe' },
      { word: 'mug', type: 'fringe' },
      { word: 'nag', type: 'fringe' },
      { word: 'nap', type: 'fringe' },
      { word: 'nod', type: 'fringe' },
      { word: 'nop', type: 'fringe' },
      { word: 'not', type: 'core' },
      { word: 'pig', type: 'fringe' },
      { word: 'pug', type: 'fringe' },
      { word: 'sag', type: 'fringe' },
      { word: 'tag', type: 'fringe' },
      { word: 'tug', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'can', from: 'Lesson 14', type: 'core' },
      { word: 'cod', from: 'Lesson 14', type: 'fringe' },
      { word: 'con', from: 'Lesson 14', type: 'fringe' },
      { word: 'cot', from: 'Lesson 14', type: 'fringe' },
      { word: 'cup', from: 'Lesson 15', type: 'fringe' },
      { word: 'cut', from: 'Lesson 15', type: 'fringe' },
      { word: 'dig', from: 'Lesson 16', type: 'fringe' },
      { word: 'dog', from: 'Lesson 16', type: 'fringe' },
      { word: 'dot', from: 'Lesson 13', type: 'fringe' },
      { word: 'dud', from: 'Lesson 15', type: 'fringe' },
      { word: 'dug', from: 'Lesson 16', type: 'fringe' },
      { word: 'fig', from: 'Lesson 16', type: 'fringe' },
      { word: 'gap', from: 'Lesson 16', type: 'fringe' },
      { word: 'gas', from: 'Lesson 16', type: 'fringe' },
      { word: 'got', from: 'Lesson 16', type: 'core' },
      { word: 'gum', from: 'Lesson 16', type: 'fringe' },
      { word: 'gut', from: 'Lesson 16', type: 'fringe' },
      { word: 'mod', from: 'Lesson 13', type: 'fringe' },
      { word: 'mud', from: 'Lesson 19', type: 'fringe' },
      { word: 'mug', from: 'Lesson 16', type: 'fringe' },
      { word: 'nag', from: 'Lesson 16', type: 'fringe' },
      { word: 'nap', from: 'Lesson 9', type: 'fringe' },
      { word: 'nod', from: 'Lesson 13', type: 'fringe' },
      { word: 'nop', from: 'Lesson 12', type: 'fringe' },
      { word: 'not', from: 'Lesson 12', type: 'core' },
      { word: 'pan', from: 'Lesson 11', type: 'fringe' },
      { word: 'pig', from: 'Lesson 16', type: 'fringe' },
      { word: 'pin', from: 'Lesson 9', type: 'fringe' },
      { word: 'pug', from: 'Lesson 16', type: 'fringe' },
      { word: 'pun', from: 'Lesson 15', type: 'fringe' },
      { word: 'pup', from: 'Lesson 15', type: 'fringe' },
      { word: 'sag', from: 'Lesson 16', type: 'fringe' },
      { word: 'sud', from: 'Lesson 15', type: 'fringe' },
      { word: 'sun', from: 'Lesson 15', type: 'fringe' },
      { word: 'tag', from: 'Lesson 16', type: 'fringe' },
      { word: 'tug', from: 'Lesson 16', type: 'fringe' },
      { word: 'um', from: 'Lesson 15', type: 'fringe' },
      { word: 'un', from: 'Lesson 15', type: 'fringe' },
      { word: 'up', from: 'Lesson 15', type: 'core' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 17,
    phoneme: '/b/',
    grapheme: 'b',
    newWords: [
      { word: 'ab', type: 'fringe' },
      { word: 'bad', type: 'fringe' },
      { word: 'bat', type: 'fringe' },
      { word: 'bid', type: 'fringe' },
      { word: 'big', type: 'fringe' },
      { word: 'bin', type: 'fringe' },
      { word: 'bit', type: 'fringe' },
      { word: 'bun', type: 'fringe' },
      { word: 'but', type: 'core' },
      { word: 'cab', type: 'fringe' },
      { word: 'cob', type: 'fringe' },
      { word: 'cub', type: 'fringe' },
      { word: 'dab', type: 'fringe' },
      { word: 'dub', type: 'fringe' },
      { word: 'gab', type: 'fringe' },
      { word: 'gob', type: 'fringe' },
      { word: 'mob', type: 'fringe' },
      { word: 'nab', type: 'fringe' },
      { word: 'nub', type: 'fringe' },
      { word: 'sad', type: 'fringe' },
      { word: 'sob', type: 'fringe' },
      { word: 'sub', type: 'fringe' },
      { word: 'tab', type: 'fringe' },
      { word: 'tad', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'tub', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ab', from: 'Lesson 17', type: 'fringe' },
      { word: 'bad', from: 'Lesson 17', type: 'fringe' },
      { word: 'bat', from: 'Lesson 17', type: 'fringe' },
      { word: 'bid', from: 'Lesson 17', type: 'fringe' },
      { word: 'big', from: 'Lesson 17', type: 'fringe' },
      { word: 'bin', from: 'Lesson 17', type: 'fringe' },
      { word: 'bit', from: 'Lesson 17', type: 'fringe' },
      { word: 'bun', from: 'Lesson 17', type: 'fringe' },
      { word: 'but', from: 'Lesson 17', type: 'core' },
      { word: 'cab', from: 'Lesson 17', type: 'fringe' },
      { word: 'cap', from: 'Lesson 14', type: 'fringe' },
      { word: 'cob', from: 'Lesson 17', type: 'fringe' },
      { word: 'cog', from: 'Lesson 16', type: 'fringe' },
      { word: 'cop', from: 'Lesson 14', type: 'fringe' },
      { word: 'cub', from: 'Lesson 17', type: 'fringe' },
      { word: 'cup', from: 'Lesson 15', type: 'fringe' },
      { word: 'cut', from: 'Lesson 15', type: 'fringe' },
      { word: 'dab', from: 'Lesson 17', type: 'fringe' },
      { word: 'did', from: 'Lesson 16', type: 'core' },
      { word: 'dig', from: 'Lesson 16', type: 'fringe' },
      { word: 'dog', from: 'Lesson 16', type: 'fringe' },
      { word: 'dub', from: 'Lesson 17', type: 'fringe' },
      { word: 'dud', from: 'Lesson 16', type: 'fringe' },
      { word: 'dug', from: 'Lesson 16', type: 'fringe' },
      { word: 'fog', from: 'Lesson 16', type: 'fringe' },
      { word: 'gab', from: 'Lesson 17', type: 'fringe' },
      { word: 'gag', from: 'Lesson 16', type: 'fringe' },
      { word: 'gap', from: 'Lesson 16', type: 'fringe' },
      { word: 'gig', from: 'Lesson 16', type: 'fringe' },
      { word: 'gob', from: 'Lesson 17', type: 'fringe' },
      { word: 'gum', from: 'Lesson 16', type: 'fringe' },
      { word: 'gut', from: 'Lesson 16', type: 'fringe' },
      { word: 'mob', from: 'Lesson 17', type: 'fringe' },
      { word: 'nab', from: 'Lesson 17', type: 'fringe' },
      { word: 'nub', from: 'Lesson 17', type: 'fringe' },
      { word: 'sad', from: 'Lesson 13', type: 'fringe' },
      { word: 'sob', from: 'Lesson 17', type: 'fringe' },
      { word: 'sub', from: 'Lesson 17', type: 'fringe' },
      { word: 'tab', from: 'Lesson 17', type: 'fringe' },
      { word: 'tad', from: 'Lesson 13', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'tub', from: 'Lesson 17', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 18,
    phoneme: '/ĕ/',
    grapheme: 'e',
    newWords: [
      { word: 'beg', type: 'fringe' },
      { word: 'Ben', type: 'fringe' },
      { word: 'bet', type: 'fringe' },
      { word: 'bug', type: 'fringe' },
      { word: 'den', type: 'fringe' },
      { word: 'get', type: 'core' },
      { word: 'Ken', type: 'fringe' },
      { word: 'meg', type: 'fringe' },
      { word: 'men', type: 'fringe' },
      { word: 'met', type: 'fringe' },
      { word: 'net', type: 'fringe' },
      { word: 'peg', type: 'fringe' },
      { word: 'pen', type: 'fringe' },
      { word: 'pet', type: 'fringe' },
      { word: 'pug', type: 'fringe' },
      { word: 'set', type: 'fringe' },
      { word: 'ten', type: 'fringe' },
      { word: 'tug', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bag', from: 'Lesson 29', type: 'fringe' },
      { word: 'beg', from: 'Lesson 18', type: 'fringe' },
      { word: 'Ben', from: 'Lesson 18', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'big', from: 'Lesson 17', type: 'fringe' },
      { word: 'bug', from: 'Lesson 18', type: 'fringe' },
      { word: 'bus', from: 'Lesson 17', type: 'fringe' },
      { word: 'but', from: 'Lesson 17', type: 'core' },
      { word: 'cab', from: 'Lesson 17', type: 'fringe' },
      { word: 'cob', from: 'Lesson 17', type: 'fringe' },
      { word: 'cub', from: 'Lesson 17', type: 'fringe' },
      { word: 'cut', from: 'Lesson 15', type: 'fringe' },
      { word: 'dab', from: 'Lesson 17', type: 'fringe' },
      { word: 'den', from: 'Lesson 18', type: 'fringe' },
      { word: 'dub', from: 'Lesson 17', type: 'fringe' },
      { word: 'get', from: 'Lesson 18', type: 'core' },
      { word: 'Ken', from: 'Lesson 18', type: 'fringe' },
      { word: 'meg', from: 'Lesson 18', type: 'fringe' },
      { word: 'men', from: 'Lesson 18', type: 'fringe' },
      { word: 'met', from: 'Lesson 18', type: 'fringe' },
      { word: 'net', from: 'Lesson 18', type: 'fringe' },
      { word: 'nub', from: 'Lesson 17', type: 'fringe' },
      { word: 'peg', from: 'Lesson 18', type: 'fringe' },
      { word: 'pen', from: 'Lesson 18', type: 'fringe' },
      { word: 'pet', from: 'Lesson 18', type: 'fringe' },
      { word: 'pug', from: 'Lesson 16', type: 'fringe' },
      { word: 'set', from: 'Lesson 18', type: 'fringe' },
      { word: 'sub', from: 'Lesson 17', type: 'fringe' },
      { word: 'tag', from: 'Lesson 16', type: 'fringe' },
      { word: 'ten', from: 'Lesson 18', type: 'fringe' },
      { word: 'tub', from: 'Lesson 17', type: 'fringe' },
      { word: 'tug', from: 'Lesson 16', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 19,
    phoneme: '',
    grapheme: 'VC & CVC',
    newWords: [
      { word: 'at', type: 'core' },
      { word: 'bad', type: 'fringe' },
      { word: 'ban', type: 'fringe' },
      { word: 'bat', type: 'fringe' },
      { word: 'bed', type: 'fringe' },
      { word: 'bin', type: 'fringe' },
      { word: 'bit', type: 'fringe' },
      { word: 'bud', type: 'fringe' },
      { word: 'bun', type: 'fringe' },
      { word: 'but', type: 'core' },
      { word: 'cat', type: 'fringe' },
      { word: 'cot', type: 'fringe' },
      { word: 'den', type: 'fringe' },
      { word: 'din', type: 'fringe' },
      { word: 'dot', type: 'fringe' },
      { word: 'dun', type: 'fringe' },
      { word: 'fat', type: 'fringe' },
      { word: 'fin', type: 'fringe' },
      { word: 'fun', type: 'fringe' },
      { word: 'got', type: 'core' },
      { word: 'in', type: 'core' },
      { word: 'mad', type: 'fringe' },
      { word: 'man', type: 'fringe' },
      { word: 'mat', type: 'fringe' },
      { word: 'men', type: 'fringe' },
      { word: 'mud', type: 'fringe' },
      { word: 'not', type: 'core' },
      { word: 'pat', type: 'fringe' },
      { word: 'pen', type: 'fringe' },
      { word: 'pin', type: 'fringe' },
      { word: 'pit', type: 'fringe' },
      { word: 'pot', type: 'fringe' },
      { word: 'pun', type: 'fringe' },
      { word: 'sat', type: 'fringe' },
      { word: 'sit', type: 'fringe' },
      { word: 'sun', type: 'fringe' },
      { word: 'ten', type: 'fringe' },
      { word: 'tin', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'at', from: 'Lesson 5', type: 'core' },
      { word: 'bad', from: 'Lesson 17', type: 'fringe' },
      { word: 'ban', from: 'Lesson 19', type: 'fringe' },
      { word: 'bat', from: 'Lesson 17', type: 'fringe' },
      { word: 'bed', from: 'Lesson 19', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'bin', from: 'Lesson 17', type: 'fringe' },
      { word: 'bit', from: 'Lesson 17', type: 'fringe' },
      { word: 'bot', from: 'Lesson 18', type: 'fringe' },
      { word: 'bud', from: 'Lesson 19', type: 'fringe' },
      { word: 'bug', from: 'Lesson 18', type: 'fringe' },
      { word: 'bun', from: 'Lesson 17', type: 'fringe' },
      { word: 'but', from: 'Lesson 17', type: 'core' },
      { word: 'cat', from: 'Lesson 14', type: 'fringe' },
      { word: 'cot', from: 'Lesson 14', type: 'fringe' },
      { word: 'den', from: 'Lesson 18', type: 'fringe' },
      { word: 'din', from: 'Lesson 19', type: 'fringe' },
      { word: 'dot', from: 'Lesson 13', type: 'fringe' },
      { word: 'dun', from: 'Lesson 15', type: 'fringe' },
      { word: 'fat', from: 'Lesson 7', type: 'fringe' },
      { word: 'fed', from: 'Lesson 28', type: 'fringe' },
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'fun', from: 'Lesson 15', type: 'fringe' },
      { word: 'get', from: 'Lesson 18', type: 'core' },
      { word: 'got', from: 'Lesson 16', type: 'core' },
      { word: 'in', from: 'Lesson 9', type: 'core' },
      { word: 'mad', from: 'Lesson 13', type: 'fringe' },
      { word: 'man', from: 'Lesson 11', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'med', from: 'Lesson 18', type: 'fringe' },
      { word: 'men', from: 'Lesson 18', type: 'fringe' },
      { word: 'mud', from: 'Lesson 19', type: 'fringe' },
      { word: 'mug', from: 'Lesson 16', type: 'fringe' },
      { word: 'net', from: 'Lesson 18', type: 'fringe' },
      { word: 'not', from: 'Lesson 12', type: 'core' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pen', from: 'Lesson 18', type: 'fringe' },
      { word: 'pin', from: 'Lesson 9', type: 'fringe' },
      { word: 'pit', from: 'Lesson 8', type: 'fringe' },
      { word: 'pot', from: 'Lesson 12', type: 'fringe' },
      { word: 'pun', from: 'Lesson 15', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'set', from: 'Lesson 18', type: 'fringe' },
      { word: 'sit', from: 'Lesson 8', type: 'fringe' },
      { word: 'sun', from: 'Lesson 15', type: 'fringe' },
      { word: 'ten', from: 'Lesson 18', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 20,
    phoneme: '/s/',
    grapheme: '-s',
    newWords: [
      { word: 'bets', type: 'fringe' },
      { word: 'bops', type: 'fringe' },
      { word: 'cap', type: 'fringe' },
      { word: 'caps', type: 'fringe' },
      { word: 'cat', type: 'fringe' },
      { word: 'cats', type: 'fringe' },
      { word: 'cops', type: 'fringe' },
      { word: 'gaps', type: 'fringe' },
      { word: 'gets', type: 'fringe' },
      { word: 'map', type: 'fringe' },
      { word: 'maps', type: 'fringe' },
      { word: 'mat', type: 'fringe' },
      { word: 'mats', type: 'fringe' },
      { word: 'mop', type: 'fringe' },
      { word: 'mops', type: 'fringe' },
      { word: 'naps', type: 'fringe' },
      { word: 'nets', type: 'fringe' },
      { word: 'pats', type: 'fringe' },
      { word: 'pets', type: 'fringe' },
      { word: 'pops', type: 'fringe' },
      { word: 'sets', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'taps', type: 'fringe' },
      { word: 'top', type: 'fringe' },
      { word: 'tops', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ban', from: 'Lesson 19', type: 'fringe' },
      { word: 'ben', from: 'Lesson 18', type: 'fringe' },
      { word: 'bets', from: 'Lesson 20', type: 'fringe' },
      { word: 'bops', from: 'Lesson 20', type: 'fringe' },
      { word: 'bun', from: 'Lesson 17', type: 'fringe' },
      { word: 'can', from: 'Lesson 14', type: 'core' },
      { word: 'cap', from: 'Lesson 14', type: 'fringe' },
      { word: 'caps', from: 'Lesson 20', type: 'fringe' },
      { word: 'cat', from: 'Lesson 14', type: 'fringe' },
      { word: 'cats', from: 'Lesson 20', type: 'fringe' },
      { word: 'cob', from: 'Lesson 17', type: 'fringe' },
      { word: 'cog', from: 'Lesson 19', type: 'fringe' },
      { word: 'con', from: 'Lesson 14', type: 'fringe' },
      { word: 'cops', from: 'Lesson 20', type: 'fringe' },
      { word: 'den', from: 'Lesson 18', type: 'fringe' },
      { word: 'fib', from: 'Lesson 19', type: 'fringe' },
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'fun', from: 'Lesson 15', type: 'fringe' },
      { word: 'gab', from: 'Lesson 17', type: 'fringe' },
      { word: 'gaps', from: 'Lesson 20', type: 'fringe' },
      { word: 'gets', from: 'Lesson 20', type: 'fringe' },
      { word: 'gob', from: 'Lesson 17', type: 'fringe' },
      { word: 'man', from: 'Lesson 11', type: 'fringe' },
      { word: 'map', from: 'Lesson 6', type: 'fringe' },
      { word: 'maps', from: 'Lesson 20', type: 'fringe' },
      { word: 'mat', from: 'Lesson 5', type: 'fringe' },
      { word: 'mats', from: 'Lesson 20', type: 'fringe' },
      { word: 'men', from: 'Lesson 18', type: 'fringe' },
      { word: 'mop', from: 'Lesson 12', type: 'fringe' },
      { word: 'mops', from: 'Lesson 20', type: 'fringe' },
      { word: 'naps', from: 'Lesson 20', type: 'fringe' },
      { word: 'nets', from: 'Lesson 20', type: 'fringe' },
      { word: 'pats', from: 'Lesson 20', type: 'fringe' },
      { word: 'pets', from: 'Lesson 20', type: 'fringe' },
      { word: 'pops', from: 'Lesson 20', type: 'fringe' },
      { word: 'sets', from: 'Lesson 20', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'taps', from: 'Lesson 20', type: 'fringe' },
      { word: 'top', from: 'Lesson 12', type: 'fringe' },
      { word: 'tops', from: 'Lesson 20', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 21,
    phoneme: '/z/',
    grapheme: '-s',
    newWords: [
      { word: 'bags', type: 'fringe' },
      { word: 'bin', type: 'fringe' },
      { word: 'bins', type: 'fringe' },
      { word: 'bugs', type: 'fringe' },
      { word: 'bun', type: 'fringe' },
      { word: 'buns', type: 'fringe' },
      { word: 'digs', type: 'fringe' },
      { word: 'figs', type: 'fringe' },
      { word: 'fin', type: 'fringe' },
      { word: 'fins', type: 'fringe' },
      { word: 'gigs', type: 'fringe' },
      { word: 'nags', type: 'fringe' },
      { word: 'pigs', type: 'fringe' },
      { word: 'pugs', type: 'fringe' },
      { word: 'sags', type: 'fringe' },
      { word: 'tag', type: 'fringe' },
      { word: 'tags', type: 'fringe' },
      { word: 'tins', type: 'fringe' },
      { word: 'tug', type: 'fringe' },
      { word: 'tugs', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bags', from: 'Lesson 21', type: 'fringe' },
      { word: 'bat', from: 'Lesson 17', type: 'fringe' },
      { word: 'bats', from: 'Lesson 20', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'bets', from: 'Lesson 20', type: 'fringe' },
      { word: 'bin', from: 'Lesson 17', type: 'fringe' },
      { word: 'bins', from: 'Lesson 21', type: 'fringe' },
      { word: 'bots', from: 'Lesson 20', type: 'fringe' },
      { word: 'bugs', from: 'Lesson 21', type: 'fringe' },
      { word: 'bun', from: 'Lesson 17', type: 'fringe' },
      { word: 'buns', from: 'Lesson 21', type: 'fringe' },
      { word: 'digs', from: 'Lesson 21', type: 'fringe' },
      { word: 'figs', from: 'Lesson 21', type: 'fringe' },
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'fins', from: 'Lesson 21', type: 'fringe' },
      { word: 'gigs', from: 'Lesson 21', type: 'fringe' },
      { word: 'nags', from: 'Lesson 21', type: 'fringe' },
      { word: 'nets', from: 'Lesson 20', type: 'fringe' },
      { word: 'pets', from: 'Lesson 20', type: 'fringe' },
      { word: 'pigs', from: 'Lesson 21', type: 'fringe' },
      { word: 'pops', from: 'Lesson 20', type: 'fringe' },
      { word: 'pots', from: 'Lesson 20', type: 'fringe' },
      { word: 'pugs', from: 'Lesson 21', type: 'fringe' },
      { word: 'pup', from: 'Lesson 20', type: 'fringe' },
      { word: 'pups', from: 'Lesson 20', type: 'fringe' },
      { word: 'sags', from: 'Lesson 21', type: 'fringe' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'set', from: 'Lesson 18', type: 'fringe' },
      { word: 'sets', from: 'Lesson 20', type: 'fringe' },
      { word: 'tag', from: 'Lesson 16', type: 'fringe' },
      { word: 'tags', from: 'Lesson 21', type: 'fringe' },
      { word: 'tins', from: 'Lesson 21', type: 'fringe' },
      { word: 'tots', from: 'Lesson 20', type: 'fringe' },
      { word: 'tug', from: 'Lesson 16', type: 'fringe' },
      { word: 'tugs', from: 'Lesson 21', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 22,
    phoneme: '/k/',
    grapheme: 'k',
    newWords: [
      { word: 'fin', type: 'fringe' },
      { word: 'kid', type: 'fringe' },
      { word: 'kids', type: 'fringe' },
      { word: 'Kim', type: 'fringe' },
      { word: 'kin', type: 'fringe' },
      { word: 'kip', type: 'fringe' },
      { word: 'kit', type: 'fringe' },
      { word: 'skid', type: 'fringe' },
      { word: 'skim', type: 'fringe' },
      { word: 'skin', type: 'fringe' },
      { word: 'skip', type: 'fringe' },
      { word: 'skit', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'taps', type: 'fringe' },
      { word: 'tin', type: 'fringe' },
      { word: 'tip', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bed', from: 'Lesson 19', type: 'fringe' },
      { word: 'beds', from: 'Lesson 21', type: 'fringe' },
      { word: 'bud', from: 'Lesson 19', type: 'fringe' },
      { word: 'buds', from: 'Lesson 21', type: 'fringe' },
      { word: 'bug', from: 'Lesson 18', type: 'fringe' },
      { word: 'bugs', from: 'Lesson 21', type: 'fringe' },
      { word: 'bun', from: 'Lesson 17', type: 'fringe' },
      { word: 'buns', from: 'Lesson 21', type: 'fringe' },
      { word: 'fin', from: 'Lesson 9', type: 'fringe' },
      { word: 'kid', from: 'Lesson 22', type: 'fringe' },
      { word: 'kids', from: 'Lesson 22', type: 'fringe' },
      { word: 'Kim', from: 'Lesson 22', type: 'fringe' },
      { word: 'kin', from: 'Lesson 22', type: 'fringe' },
      { word: 'kip', from: 'Lesson 22', type: 'fringe' },
      { word: 'kit', from: 'Lesson 22', type: 'fringe' },
      { word: 'pad', from: 'Lesson 13', type: 'fringe' },
      { word: 'pads', from: 'Lesson 21', type: 'fringe' },
      { word: 'pans', from: 'Lesson 21', type: 'fringe' },
      { word: 'pat', from: 'Lesson 6', type: 'fringe' },
      { word: 'pats', from: 'Lesson 20', type: 'fringe' },
      { word: 'pins', from: 'Lesson 21', type: 'fringe' },
      { word: 'pods', from: 'Lesson 21', type: 'fringe' },
      { word: 'puns', from: 'Lesson 21', type: 'fringe' },
      { word: 'skid', from: 'Lesson 22', type: 'fringe' },
      { word: 'skim', from: 'Lesson 22', type: 'fringe' },
      { word: 'skin', from: 'Lesson 22', type: 'fringe' },
      { word: 'skip', from: 'Lesson 22', type: 'fringe' },
      { word: 'skit', from: 'Lesson 22', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'taps', from: 'Lesson 20', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
      { word: 'tip', from: 'Lesson 8', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 23,
    phoneme: '/h/',
    grapheme: 'h',
    newWords: [
      { word: 'get', type: 'core' },
      { word: 'got', type: 'core' },
      { word: 'had', type: 'core' },
      { word: 'has', type: 'core' },
      { word: 'hat', type: 'fringe' },
      { word: 'hid', type: 'core' },
      { word: 'him', type: 'core' },
      { word: 'hip', type: 'fringe' },
      { word: 'his', type: 'core' },
      { word: 'hit', type: 'core' },
      { word: 'hog', type: 'fringe' },
      { word: 'hop', type: 'fringe' },
      { word: 'hot', type: 'fringe' },
      { word: 'hug', type: 'fringe' },
      { word: 'hum', type: 'fringe' },
      { word: 'hut', type: 'fringe' },
      { word: 'net', type: 'fringe' },
      { word: 'not', type: 'core' },
    ],
    reviewWords: [
      { word: 'as', from: 'Lesson 22', type: 'core' },
      { word: 'ask', from: 'Lesson 22', type: 'core' },
      { word: 'at', from: 'Lesson 5', type: 'core' },
      { word: 'desk', from: 'Lesson 22', type: 'fringe' },
      { word: 'disk', from: 'Lesson 22', type: 'fringe' },
      { word: 'dusk', from: 'Lesson 22', type: 'fringe' },
      { word: 'get', from: 'Lesson 18', type: 'core' },
      { word: 'got', from: 'Lesson 16', type: 'core' },
      { word: 'had', from: 'Lesson 23', type: 'core' },
      { word: 'has', from: 'Lesson 23', type: 'core' },
      { word: 'hat', from: 'Lesson 23', type: 'fringe' },
      { word: 'hid', from: 'Lesson 23', type: 'core' },
      { word: 'him', from: 'Lesson 23', type: 'core' },
      { word: 'hip', from: 'Lesson 23', type: 'fringe' },
      { word: 'his', from: 'Lesson 23', type: 'core' },
      { word: 'hit', from: 'Lesson 23', type: 'core' },
      { word: 'hog', from: 'Lesson 23', type: 'fringe' },
      { word: 'hop', from: 'Lesson 23', type: 'fringe' },
      { word: 'hot', from: 'Lesson 23', type: 'fringe' },
      { word: 'hug', from: 'Lesson 23', type: 'fringe' },
      { word: 'hum', from: 'Lesson 23', type: 'fringe' },
      { word: 'hut', from: 'Lesson 23', type: 'fringe' },
      { word: 'kid', from: 'Lesson 22', type: 'fringe' },
      { word: 'kids', from: 'Lesson 22', type: 'fringe' },
      { word: 'kin', from: 'Lesson 22', type: 'fringe' },
      { word: 'kit', from: 'Lesson 22', type: 'fringe' },
      { word: 'kits', from: 'Lesson 22', type: 'fringe' },
      { word: 'mask', from: 'Lesson 22', type: 'fringe' },
      { word: 'net', from: 'Lesson 18', type: 'fringe' },
      { word: 'not', from: 'Lesson 12', type: 'core' },
      { word: 'sat', from: 'Lesson 5', type: 'fringe' },
      { word: 'sit', from: 'Lesson 8', type: 'fringe' },
      { word: 'skit', from: 'Lesson 22', type: 'fringe' },
      { word: 'task', from: 'Lesson 22', type: 'fringe' },
      { word: 'tusk', from: 'Lesson 22', type: 'fringe' },
    ],
    heartWords: ["has","his"],
    morphologyNotes: [
    ],
  },

  {
    number: 24,
    phoneme: '/r/',
    grapheme: 'r',
    newWords: [
      { word: 'bat', type: 'fringe' },
      { word: 'bed', type: 'fringe' },
      { word: 'bet', type: 'fringe' },
      { word: 'rag', type: 'fringe' },
      { word: 'rags', type: 'fringe' },
      { word: 'rap', type: 'fringe' },
      { word: 'rat', type: 'fringe' },
      { word: 'red', type: 'fringe' },
      { word: 'rid', type: 'fringe' },
      { word: 'rig', type: 'fringe' },
      { word: 'rim', type: 'fringe' },
      { word: 'rip', type: 'fringe' },
      { word: 'rod', type: 'fringe' },
      { word: 'rug', type: 'fringe' },
      { word: 'rugs', type: 'fringe' },
      { word: 'run', type: 'fringe' },
      { word: 'runs', type: 'fringe' },
      { word: 'rut', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bat', from: 'Lesson 17', type: 'fringe' },
      { word: 'bed', from: 'Lesson 19', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'ham', from: 'Lesson 23', type: 'fringe' },
      { word: 'hem', from: 'Lesson 23', type: 'fringe' },
      { word: 'him', from: 'Lesson 23', type: 'core' },
      { word: 'hint', from: 'Lesson 23', type: 'fringe' },
      { word: 'hit', from: 'Lesson 23', type: 'core' },
      { word: 'hub', from: 'Lesson 23', type: 'fringe' },
      { word: 'hug', from: 'Lesson 23', type: 'fringe' },
      { word: 'hum', from: 'Lesson 23', type: 'fringe' },
      { word: 'hunt', from: 'Lesson 23', type: 'fringe' },
      { word: 'hut', from: 'Lesson 23', type: 'fringe' },
      { word: 'Kim', from: 'Lesson 22', type: 'fringe' },
      { word: 'mug', from: 'Lesson 16', type: 'fringe' },
      { word: 'rag', from: 'Lesson 24', type: 'fringe' },
      { word: 'rags', from: 'Lesson 24', type: 'fringe' },
      { word: 'rap', from: 'Lesson 24', type: 'fringe' },
      { word: 'rat', from: 'Lesson 24', type: 'fringe' },
      { word: 'red', from: 'Lesson 24', type: 'fringe' },
      { word: 'rid', from: 'Lesson 24', type: 'fringe' },
      { word: 'rig', from: 'Lesson 24', type: 'fringe' },
      { word: 'rim', from: 'Lesson 24', type: 'fringe' },
      { word: 'rip', from: 'Lesson 24', type: 'fringe' },
      { word: 'rod', from: 'Lesson 24', type: 'fringe' },
      { word: 'rug', from: 'Lesson 24', type: 'fringe' },
      { word: 'rugs', from: 'Lesson 24', type: 'fringe' },
      { word: 'run', from: 'Lesson 24', type: 'fringe' },
      { word: 'runs', from: 'Lesson 24', type: 'fringe' },
      { word: 'rut', from: 'Lesson 24', type: 'fringe' },
      { word: 'snub', from: 'Lesson 23', type: 'fringe' },
      { word: 'snug', from: 'Lesson 23', type: 'fringe' },
      { word: 'stub', from: 'Lesson 23', type: 'fringe' },
      { word: 'sub', from: 'Lesson 17', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 25,
    phoneme: '/r/',
    grapheme: 'r',
    newWords: [
      { word: 'brim', type: 'fringe' },
      { word: 'crab', type: 'fringe' },
      { word: 'crib', type: 'fringe' },
      { word: 'crop', type: 'fringe' },
      { word: 'drip', type: 'fringe' },
      { word: 'drips', type: 'fringe' },
      { word: 'drop', type: 'fringe' },
      { word: 'grab', type: 'fringe' },
      { word: 'gram', type: 'fringe' },
      { word: 'grim', type: 'fringe' },
      { word: 'grip', type: 'fringe' },
      { word: 'grips', type: 'fringe' },
      { word: 'prim', type: 'fringe' },
      { word: 'prod', type: 'fringe' },
      { word: 'prop', type: 'fringe' },
      { word: 'trim', type: 'fringe' },
      { word: 'trip', type: 'fringe' },
      { word: 'trips', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'brim', from: 'Lesson 25', type: 'fringe' },
      { word: 'can', from: 'Lesson 14', type: 'core' },
      { word: 'crab', from: 'Lesson 25', type: 'fringe' },
      { word: 'crib', from: 'Lesson 25', type: 'fringe' },
      { word: 'crop', from: 'Lesson 25', type: 'fringe' },
      { word: 'drip', from: 'Lesson 25', type: 'fringe' },
      { word: 'drips', from: 'Lesson 25', type: 'fringe' },
      { word: 'drop', from: 'Lesson 25', type: 'fringe' },
      { word: 'grab', from: 'Lesson 25', type: 'fringe' },
      { word: 'gram', from: 'Lesson 25', type: 'fringe' },
      { word: 'grim', from: 'Lesson 25', type: 'fringe' },
      { word: 'grip', from: 'Lesson 25', type: 'fringe' },
      { word: 'grips', from: 'Lesson 25', type: 'fringe' },
      { word: 'prim', from: 'Lesson 25', type: 'fringe' },
      { word: 'prod', from: 'Lesson 25', type: 'fringe' },
      { word: 'prop', from: 'Lesson 25', type: 'fringe' },
      { word: 'ram', from: 'Lesson 24', type: 'fringe' },
      { word: 'ramp', from: 'Lesson 24', type: 'fringe' },
      { word: 'ran', from: 'Lesson 24', type: 'fringe' },
      { word: 'rant', from: 'Lesson 24', type: 'fringe' },
      { word: 'rap', from: 'Lesson 24', type: 'fringe' },
      { word: 'raps', from: 'Lesson 24', type: 'fringe' },
      { word: 'rasp', from: 'Lesson 24', type: 'fringe' },
      { word: 'rent', from: 'Lesson 24', type: 'fringe' },
      { word: 'runt', from: 'Lesson 24', type: 'fringe' },
      { word: 'rut', from: 'Lesson 24', type: 'fringe' },
      { word: 'sam', from: 'Lesson 11', type: 'fringe' },
      { word: 'scan', from: 'Lesson 24', type: 'fringe' },
      { word: 'spam', from: 'Lesson 24', type: 'fringe' },
      { word: 'span', from: 'Lesson 24', type: 'fringe' },
      { word: 'trim', from: 'Lesson 25', type: 'fringe' },
      { word: 'trip', from: 'Lesson 25', type: 'fringe' },
      { word: 'trips', from: 'Lesson 25', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 26,
    phoneme: '/l/',
    grapheme: 'l',
    newWords: [
      { word: 'bed', type: 'fringe' },
      { word: 'bet', type: 'fringe' },
      { word: 'lab', type: 'fringe' },
      { word: 'lad', type: 'fringe' },
      { word: 'lag', type: 'fringe' },
      { word: 'lamp', type: 'fringe' },
      { word: 'lap', type: 'fringe' },
      { word: 'laps', type: 'fringe' },
      { word: 'led', type: 'fringe' },
      { word: 'leg', type: 'fringe' },
      { word: 'let', type: 'fringe' },
      { word: 'lid', type: 'fringe' },
      { word: 'limp', type: 'fringe' },
      { word: 'lip', type: 'fringe' },
      { word: 'lips', type: 'fringe' },
      { word: 'lit', type: 'fringe' },
      { word: 'log', type: 'fringe' },
      { word: 'lot', type: 'fringe' },
      { word: 'lug', type: 'fringe' },
      { word: 'lump', type: 'fringe' },
      { word: 'red', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bag', from: 'Lesson 29', type: 'fringe' },
      { word: 'bed', from: 'Lesson 19', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'brag', from: 'Lesson 25', type: 'fringe' },
      { word: 'cog', from: 'Lesson 25', type: 'fringe' },
      { word: 'cop', from: 'Lesson 14', type: 'fringe' },
      { word: 'crop', from: 'Lesson 25', type: 'fringe' },
      { word: 'drop', from: 'Lesson 25', type: 'fringe' },
      { word: 'fog', from: 'Lesson 25', type: 'fringe' },
      { word: 'frog', from: 'Lesson 25', type: 'fringe' },
      { word: 'grip', from: 'Lesson 25', type: 'fringe' },
      { word: 'lab', from: 'Lesson 26', type: 'fringe' },
      { word: 'lad', from: 'Lesson 26', type: 'fringe' },
      { word: 'lag', from: 'Lesson 26', type: 'fringe' },
      { word: 'lamp', from: 'Lesson 26', type: 'fringe' },
      { word: 'lap', from: 'Lesson 26', type: 'fringe' },
      { word: 'laps', from: 'Lesson 26', type: 'fringe' },
      { word: 'led', from: 'Lesson 26', type: 'fringe' },
      { word: 'leg', from: 'Lesson 26', type: 'fringe' },
      { word: 'let', from: 'Lesson 26', type: 'fringe' },
      { word: 'lid', from: 'Lesson 26', type: 'fringe' },
      { word: 'limp', from: 'Lesson 26', type: 'fringe' },
      { word: 'lip', from: 'Lesson 26', type: 'fringe' },
      { word: 'lips', from: 'Lesson 26', type: 'fringe' },
      { word: 'lit', from: 'Lesson 26', type: 'fringe' },
      { word: 'log', from: 'Lesson 26', type: 'fringe' },
      { word: 'lot', from: 'Lesson 26', type: 'fringe' },
      { word: 'lug', from: 'Lesson 26', type: 'fringe' },
      { word: 'lump', from: 'Lesson 26', type: 'fringe' },
      { word: 'prep', from: 'Lesson 25', type: 'fringe' },
      { word: 'prop', from: 'Lesson 25', type: 'fringe' },
      { word: 'rag', from: 'Lesson 24', type: 'fringe' },
      { word: 'red', from: 'Lesson 24', type: 'fringe' },
      { word: 'rep', from: 'Lesson 25', type: 'fringe' },
      { word: 'rip', from: 'Lesson 24', type: 'fringe' },
      { word: 'tag', from: 'Lesson 16', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'trap', from: 'Lesson 25', type: 'fringe' },
      { word: 'trip', from: 'Lesson 25', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 27,
    phoneme: '/l/',
    grapheme: 'l',
    newWords: [
      { word: 'blot', type: 'fringe' },
      { word: 'clap', type: 'fringe' },
      { word: 'clog', type: 'fringe' },
      { word: 'clop', type: 'fringe' },
      { word: 'clot', type: 'fringe' },
      { word: 'flag', type: 'fringe' },
      { word: 'flat', type: 'fringe' },
      { word: 'flip', type: 'fringe' },
      { word: 'flop', type: 'fringe' },
      { word: 'glop', type: 'fringe' },
      { word: 'lag', type: 'fringe' },
      { word: 'lip', type: 'fringe' },
      { word: 'lug', type: 'fringe' },
      { word: 'plog', type: 'fringe' },
      { word: 'plop', type: 'fringe' },
      { word: 'plot', type: 'fringe' },
      { word: 'plug', type: 'fringe' },
      { word: 'slap', type: 'fringe' },
      { word: 'slip', type: 'fringe' },
      { word: 'slob', type: 'fringe' },
      { word: 'slot', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'blot', from: 'Lesson 27', type: 'fringe' },
      { word: 'clap', from: 'Lesson 27', type: 'fringe' },
      { word: 'clog', from: 'Lesson 27', type: 'fringe' },
      { word: 'clop', from: 'Lesson 27', type: 'fringe' },
      { word: 'clot', from: 'Lesson 27', type: 'fringe' },
      { word: 'flag', from: 'Lesson 27', type: 'fringe' },
      { word: 'flat', from: 'Lesson 27', type: 'fringe' },
      { word: 'flip', from: 'Lesson 27', type: 'fringe' },
      { word: 'flop', from: 'Lesson 27', type: 'fringe' },
      { word: 'glop', from: 'Lesson 27', type: 'fringe' },
      { word: 'hip', from: 'Lesson 23', type: 'fringe' },
      { word: 'hit', from: 'Lesson 23', type: 'core' },
      { word: 'kit', from: 'Lesson 22', type: 'fringe' },
      { word: 'lad', from: 'Lesson 26', type: 'fringe' },
      { word: 'lag', from: 'Lesson 26', type: 'fringe' },
      { word: 'lamp', from: 'Lesson 26', type: 'fringe' },
      { word: 'land', from: 'Lesson 26', type: 'fringe' },
      { word: 'lap', from: 'Lesson 26', type: 'fringe' },
      { word: 'left', from: 'Lesson 26', type: 'fringe' },
      { word: 'lend', from: 'Lesson 26', type: 'fringe' },
      { word: 'let', from: 'Lesson 26', type: 'fringe' },
      { word: 'lift', from: 'Lesson 26', type: 'fringe' },
      { word: 'limp', from: 'Lesson 26', type: 'fringe' },
      { word: 'lip', from: 'Lesson 26', type: 'fringe' },
      { word: 'lit', from: 'Lesson 26', type: 'fringe' },
      { word: 'loft', from: 'Lesson 26', type: 'fringe' },
      { word: 'lug', from: 'Lesson 26', type: 'fringe' },
      { word: 'plog', from: 'Lesson 27', type: 'fringe' },
      { word: 'plop', from: 'Lesson 27', type: 'fringe' },
      { word: 'plot', from: 'Lesson 27', type: 'fringe' },
      { word: 'plug', from: 'Lesson 27', type: 'fringe' },
      { word: 'rip', from: 'Lesson 24', type: 'fringe' },
      { word: 'slap', from: 'Lesson 27', type: 'fringe' },
      { word: 'slip', from: 'Lesson 27', type: 'fringe' },
      { word: 'slob', from: 'Lesson 27', type: 'fringe' },
      { word: 'slot', from: 'Lesson 27', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 28,
    phoneme: '/w/',
    grapheme: 'w',
    newWords: [
      { word: 'den', type: 'fringe' },
      { word: 'dent', type: 'fringe' },
      { word: 'fed', type: 'fringe' },
      { word: 'led', type: 'fringe' },
      { word: 'let', type: 'fringe' },
      { word: 'swag', type: 'fringe' },
      { word: 'ten', type: 'fringe' },
      { word: 'tin', type: 'fringe' },
      { word: 'twig', type: 'fringe' },
      { word: 'twin', type: 'fringe' },
      { word: 'wag', type: 'fringe' },
      { word: 'web', type: 'fringe' },
      { word: 'wed', type: 'fringe' },
      { word: 'wen', type: 'fringe' },
      { word: 'went', type: 'fringe' },
      { word: 'west', type: 'fringe' },
      { word: 'wet', type: 'fringe' },
      { word: 'wig', type: 'fringe' },
      { word: 'win', type: 'fringe' },
      { word: 'wit', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bed', from: 'Lesson 19', type: 'fringe' },
      { word: 'belt', from: 'Lesson 27', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'bled', from: 'Lesson 27', type: 'fringe' },
      { word: 'den', from: 'Lesson 18', type: 'fringe' },
      { word: 'dent', from: 'Lesson 28', type: 'fringe' },
      { word: 'fed', from: 'Lesson 28', type: 'fringe' },
      { word: 'felp', from: 'Lesson 27', type: 'fringe' },
      { word: 'felt', from: 'Lesson 27', type: 'fringe' },
      { word: 'fled', from: 'Lesson 27', type: 'fringe' },
      { word: 'held', from: 'Lesson 27', type: 'fringe' },
      { word: 'help', from: 'Lesson 27', type: 'fringe' },
      { word: 'led', from: 'Lesson 26', type: 'fringe' },
      { word: 'let', from: 'Lesson 26', type: 'fringe' },
      { word: 'lid', from: 'Lesson 26', type: 'fringe' },
      { word: 'pled', from: 'Lesson 27', type: 'fringe' },
      { word: 'red', from: 'Lesson 24', type: 'fringe' },
      { word: 'sled', from: 'Lesson 27', type: 'fringe' },
      { word: 'slid', from: 'Lesson 27', type: 'fringe' },
      { word: 'swag', from: 'Lesson 28', type: 'fringe' },
      { word: 'ten', from: 'Lesson 18', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
      { word: 'twig', from: 'Lesson 28', type: 'fringe' },
      { word: 'twin', from: 'Lesson 28', type: 'fringe' },
      { word: 'wag', from: 'Lesson 28', type: 'fringe' },
      { word: 'web', from: 'Lesson 28', type: 'fringe' },
      { word: 'wed', from: 'Lesson 28', type: 'fringe' },
      { word: 'wen', from: 'Lesson 28', type: 'fringe' },
      { word: 'went', from: 'Lesson 28', type: 'fringe' },
      { word: 'west', from: 'Lesson 28', type: 'fringe' },
      { word: 'wet', from: 'Lesson 28', type: 'fringe' },
      { word: 'wig', from: 'Lesson 28', type: 'fringe' },
      { word: 'win', from: 'Lesson 28', type: 'fringe' },
      { word: 'wit', from: 'Lesson 28', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 29,
    phoneme: '/j/',
    grapheme: 'j',
    newWords: [
      { word: 'bag', type: 'fringe' },
      { word: 'bug', type: 'fringe' },
      { word: 'jab', type: 'fringe' },
      { word: 'jag', type: 'fringe' },
      { word: 'jam', type: 'fringe' },
      { word: 'Jan', type: 'fringe' },
      { word: 'jest', type: 'fringe' },
      { word: 'jet', type: 'fringe' },
      { word: 'jig', type: 'fringe' },
      { word: 'Jim', type: 'fringe' },
      { word: 'job', type: 'fringe' },
      { word: 'jog', type: 'fringe' },
      { word: 'Jon', type: 'fringe' },
      { word: 'jot', type: 'fringe' },
      { word: 'jug', type: 'fringe' },
      { word: 'just', type: 'core' },
      { word: 'jut', type: 'fringe' },
      { word: 'wag', type: 'fringe' },
      { word: 'wig', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'bag', from: 'Lesson 29', type: 'fringe' },
      { word: 'bug', from: 'Lesson 18', type: 'fringe' },
      { word: 'jab', from: 'Lesson 29', type: 'fringe' },
      { word: 'jag', from: 'Lesson 29', type: 'fringe' },
      { word: 'jam', from: 'Lesson 29', type: 'fringe' },
      { word: 'Jan', from: 'Lesson 29', type: 'fringe' },
      { word: 'jest', from: 'Lesson 29', type: 'fringe' },
      { word: 'jet', from: 'Lesson 29', type: 'fringe' },
      { word: 'jig', from: 'Lesson 29', type: 'fringe' },
      { word: 'Jim', from: 'Lesson 29', type: 'fringe' },
      { word: 'job', from: 'Lesson 29', type: 'fringe' },
      { word: 'jog', from: 'Lesson 29', type: 'fringe' },
      { word: 'Jon', from: 'Lesson 29', type: 'fringe' },
      { word: 'jot', from: 'Lesson 29', type: 'fringe' },
      { word: 'jug', from: 'Lesson 29', type: 'fringe' },
      { word: 'just', from: 'Lesson 29', type: 'core' },
      { word: 'jut', from: 'Lesson 29', type: 'fringe' },
      { word: 'kept', from: 'Lesson 28', type: 'fringe' },
      { word: 'lept', from: 'Lesson 28', type: 'fringe' },
      { word: 'let', from: 'Lesson 26', type: 'fringe' },
      { word: 'lit', from: 'Lesson 26', type: 'fringe' },
      { word: 'swig', from: 'Lesson 28', type: 'fringe' },
      { word: 'twig', from: 'Lesson 28', type: 'fringe' },
      { word: 'twin', from: 'Lesson 28', type: 'fringe' },
      { word: 'wag', from: 'Lesson 28', type: 'fringe' },
      { word: 'wed', from: 'Lesson 28', type: 'fringe' },
      { word: 'weld', from: 'Lesson 28', type: 'fringe' },
      { word: 'welt', from: 'Lesson 28', type: 'fringe' },
      { word: 'wept', from: 'Lesson 28', type: 'fringe' },
      { word: 'wet', from: 'Lesson 28', type: 'fringe' },
      { word: 'wig', from: 'Lesson 28', type: 'fringe' },
      { word: 'win', from: 'Lesson 28', type: 'fringe' },
      { word: 'wit', from: 'Lesson 28', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 30,
    phoneme: '/y/',
    grapheme: 'y',
    newWords: [
      { word: 'best', type: 'fringe' },
      { word: 'bet', type: 'fringe' },
      { word: 'get', type: 'core' },
      { word: 'gum', type: 'fringe' },
      { word: 'gut', type: 'fringe' },
      { word: 'jet', type: 'fringe' },
      { word: 'rest', type: 'fringe' },
      { word: 'sum', type: 'fringe' },
      { word: 'west', type: 'fringe' },
      { word: 'wet', type: 'fringe' },
      { word: 'yam', type: 'fringe' },
      { word: 'yen', type: 'fringe' },
      { word: 'yep', type: 'fringe' },
      { word: 'yes', type: 'core' },
      { word: 'yet', type: 'fringe' },
      { word: 'yum', type: 'fringe' },
      { word: 'yup', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'best', from: 'Lesson 30', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'get', from: 'Lesson 18', type: 'core' },
      { word: 'gum', from: 'Lesson 16', type: 'fringe' },
      { word: 'gut', from: 'Lesson 16', type: 'fringe' },
      { word: 'jab', from: 'Lesson 29', type: 'fringe' },
      { word: 'jabs', from: 'Lesson 29', type: 'fringe' },
      { word: 'jest', from: 'Lesson 29', type: 'fringe' },
      { word: 'jet', from: 'Lesson 29', type: 'fringe' },
      { word: 'jilt', from: 'Lesson 29', type: 'fringe' },
      { word: 'jobs', from: 'Lesson 29', type: 'fringe' },
      { word: 'jot', from: 'Lesson 29', type: 'fringe' },
      { word: 'jots', from: 'Lesson 29', type: 'fringe' },
      { word: 'just', from: 'Lesson 29', type: 'core' },
      { word: 'jut', from: 'Lesson 29', type: 'fringe' },
      { word: 'rest', from: 'Lesson 30', type: 'fringe' },
      { word: 'sum', from: 'Lesson 15', type: 'fringe' },
      { word: 'went', from: 'Lesson 28', type: 'fringe' },
      { word: 'wept', from: 'Lesson 29', type: 'fringe' },
      { word: 'west', from: 'Lesson 28', type: 'fringe' },
      { word: 'wet', from: 'Lesson 28', type: 'fringe' },
      { word: 'wilt', from: 'Lesson 32', type: 'fringe' },
      { word: 'wit', from: 'Lesson 28', type: 'fringe' },
      { word: 'yam', from: 'Lesson 30', type: 'fringe' },
      { word: 'yen', from: 'Lesson 30', type: 'fringe' },
      { word: 'yep', from: 'Lesson 30', type: 'fringe' },
      { word: 'yes', from: 'Lesson 30', type: 'core' },
      { word: 'yet', from: 'Lesson 30', type: 'fringe' },
      { word: 'yum', from: 'Lesson 30', type: 'fringe' },
      { word: 'yup', from: 'Lesson 30', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 31,
    phoneme: '/ks/',
    grapheme: 'x',
    newWords: [
      { word: 'ax', type: 'fringe' },
      { word: 'beg', type: 'fringe' },
      { word: 'bet', type: 'fringe' },
      { word: 'big', type: 'fringe' },
      { word: 'box', type: 'fringe' },
      { word: 'fax', type: 'fringe' },
      { word: 'fix', type: 'fringe' },
      { word: 'flax', type: 'fringe' },
      { word: 'fox', type: 'fringe' },
      { word: 'lax', type: 'fringe' },
      { word: 'lox', type: 'fringe' },
      { word: 'max', type: 'fringe' },
      { word: 'mix', type: 'fringe' },
      { word: 'net', type: 'fringe' },
      { word: 'next', type: 'fringe' },
      { word: 'ox', type: 'fringe' },
      { word: 'pox', type: 'fringe' },
      { word: 'sax', type: 'fringe' },
      { word: 'six', type: 'fringe' },
      { word: 'tax', type: 'fringe' },
      { word: 'tux', type: 'fringe' },
      { word: 'wag', type: 'fringe' },
      { word: 'wax', type: 'fringe' },
      { word: 'wig', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ax', from: 'Lesson 31', type: 'fringe' },
      { word: 'beg', from: 'Lesson 18', type: 'fringe' },
      { word: 'bet', from: 'Lesson 18', type: 'fringe' },
      { word: 'big', from: 'Lesson 17', type: 'fringe' },
      { word: 'box', from: 'Lesson 31', type: 'fringe' },
      { word: 'fax', from: 'Lesson 31', type: 'fringe' },
      { word: 'fix', from: 'Lesson 31', type: 'fringe' },
      { word: 'flax', from: 'Lesson 31', type: 'fringe' },
      { word: 'fox', from: 'Lesson 31', type: 'fringe' },
      { word: 'held', from: 'Lesson 30', type: 'fringe' },
      { word: 'help', from: 'Lesson 30', type: 'fringe' },
      { word: 'lax', from: 'Lesson 31', type: 'fringe' },
      { word: 'lox', from: 'Lesson 31', type: 'fringe' },
      { word: 'max', from: 'Lesson 31', type: 'fringe' },
      { word: 'mix', from: 'Lesson 31', type: 'fringe' },
      { word: 'net', from: 'Lesson 18', type: 'fringe' },
      { word: 'next', from: 'Lesson 31', type: 'fringe' },
      { word: 'ox', from: 'Lesson 31', type: 'fringe' },
      { word: 'pox', from: 'Lesson 31', type: 'fringe' },
      { word: 'sax', from: 'Lesson 31', type: 'fringe' },
      { word: 'six', from: 'Lesson 31', type: 'fringe' },
      { word: 'tax', from: 'Lesson 31', type: 'fringe' },
      { word: 'tux', from: 'Lesson 31', type: 'fringe' },
      { word: 'wag', from: 'Lesson 28', type: 'fringe' },
      { word: 'wax', from: 'Lesson 31', type: 'fringe' },
      { word: 'weld', from: 'Lesson 30', type: 'fringe' },
      { word: 'welp', from: 'Lesson 30', type: 'fringe' },
      { word: 'welt', from: 'Lesson 30', type: 'fringe' },
      { word: 'wet', from: 'Lesson 28', type: 'fringe' },
      { word: 'wig', from: 'Lesson 28', type: 'fringe' },
      { word: 'yam', from: 'Lesson 30', type: 'fringe' },
      { word: 'yap', from: 'Lesson 30', type: 'fringe' },
      { word: 'yelp', from: 'Lesson 30', type: 'fringe' },
      { word: 'yep', from: 'Lesson 30', type: 'fringe' },
      { word: 'yes', from: 'Lesson 30', type: 'core' },
      { word: 'yest', from: 'Lesson 30', type: 'fringe' },
      { word: 'yet', from: 'Lesson 30', type: 'fringe' },
      { word: 'yip', from: 'Lesson 30', type: 'fringe' },
      { word: 'yup', from: 'Lesson 30', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 32,
    phoneme: '/kw/',
    grapheme: 'qu',
    newWords: [
      { word: 'best', type: 'fringe' },
      { word: 'lip', type: 'fringe' },
      { word: 'quest', type: 'fringe' },
      { word: 'quid', type: 'fringe' },
      { word: 'quilt', type: 'fringe' },
      { word: 'quip', type: 'fringe' },
      { word: 'quit', type: 'fringe' },
      { word: 'slip', type: 'fringe' },
      { word: 'squib', type: 'fringe' },
      { word: 'squid', type: 'fringe' },
      { word: 'west', type: 'fringe' },
      { word: 'wilt', type: 'fringe' },
      { word: 'wist', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'best', from: 'Lesson 30', type: 'fringe' },
      { word: 'ex', from: 'Lesson 31', type: 'fringe' },
      { word: 'fox', from: 'Lesson 31', type: 'fringe' },
      { word: 'jax', from: 'Lesson 31', type: 'fringe' },
      { word: 'lag', from: 'Lesson 26', type: 'fringe' },
      { word: 'lap', from: 'Lesson 26', type: 'fringe' },
      { word: 'lax', from: 'Lesson 31', type: 'fringe' },
      { word: 'lex', from: 'Lesson 31', type: 'fringe' },
      { word: 'lip', from: 'Lesson 26', type: 'fringe' },
      { word: 'nix', from: 'Lesson 31', type: 'fringe' },
      { word: 'ox', from: 'Lesson 31', type: 'fringe' },
      { word: 'pox', from: 'Lesson 31', type: 'fringe' },
      { word: 'quest', from: 'Lesson 32', type: 'fringe' },
      { word: 'quid', from: 'Lesson 32', type: 'fringe' },
      { word: 'quilt', from: 'Lesson 32', type: 'fringe' },
      { word: 'quip', from: 'Lesson 32', type: 'fringe' },
      { word: 'quit', from: 'Lesson 32', type: 'fringe' },
      { word: 'sip', from: 'Lesson 8', type: 'fringe' },
      { word: 'six', from: 'Lesson 31', type: 'fringe' },
      { word: 'slip', from: 'Lesson 27', type: 'fringe' },
      { word: 'squib', from: 'Lesson 32', type: 'fringe' },
      { word: 'squid', from: 'Lesson 32', type: 'fringe' },
      { word: 'wag', from: 'Lesson 28', type: 'fringe' },
      { word: 'wax', from: 'Lesson 31', type: 'fringe' },
      { word: 'west', from: 'Lesson 28', type: 'fringe' },
      { word: 'wilt', from: 'Lesson 32', type: 'fringe' },
      { word: 'wist', from: 'Lesson 32', type: 'fringe' },
      { word: 'yap', from: 'Lesson 31', type: 'fringe' },
      { word: 'yip', from: 'Lesson 31', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 33,
    phoneme: '/v/',
    grapheme: 'v',
    newWords: [
      { word: 'end', type: 'fringe' },
      { word: 'fend', type: 'fringe' },
      { word: 'tan', type: 'fringe' },
      { word: 'ten', type: 'fringe' },
      { word: 'tend', type: 'fringe' },
      { word: 'van', type: 'fringe' },
      { word: 'vast', type: 'fringe' },
      { word: 'vat', type: 'fringe' },
      { word: 'vend', type: 'fringe' },
      { word: 'vent', type: 'fringe' },
      { word: 'vest', type: 'fringe' },
      { word: 'vet', type: 'fringe' },
      { word: 'vin', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'end', from: 'Lesson 33', type: 'fringe' },
      { word: 'fend', from: 'Lesson 33', type: 'fringe' },
      { word: 'kilt', from: 'Lesson 32', type: 'fringe' },
      { word: 'kit', from: 'Lesson 22', type: 'fringe' },
      { word: 'quest', from: 'Lesson 32', type: 'fringe' },
      { word: 'quid', from: 'Lesson 32', type: 'fringe' },
      { word: 'quilt', from: 'Lesson 32', type: 'fringe' },
      { word: 'quip', from: 'Lesson 32', type: 'fringe' },
      { word: 'quips', from: 'Lesson 32', type: 'fringe' },
      { word: 'quit', from: 'Lesson 32', type: 'fringe' },
      { word: 'quits', from: 'Lesson 32', type: 'fringe' },
      { word: 'tan', from: 'Lesson 11', type: 'fringe' },
      { word: 'ten', from: 'Lesson 18', type: 'fringe' },
      { word: 'tend', from: 'Lesson 33', type: 'fringe' },
      { word: 'van', from: 'Lesson 33', type: 'fringe' },
      { word: 'vast', from: 'Lesson 33', type: 'fringe' },
      { word: 'vat', from: 'Lesson 33', type: 'fringe' },
      { word: 'vend', from: 'Lesson 33', type: 'fringe' },
      { word: 'vent', from: 'Lesson 33', type: 'fringe' },
      { word: 'vest', from: 'Lesson 33', type: 'fringe' },
      { word: 'vet', from: 'Lesson 33', type: 'fringe' },
      { word: 'vin', from: 'Lesson 33', type: 'fringe' },
      { word: 'welt', from: 'Lesson 32', type: 'fringe' },
      { word: 'wes', from: 'Lesson 32', type: 'fringe' },
      { word: 'west', from: 'Lesson 28', type: 'fringe' },
      { word: 'wilt', from: 'Lesson 32', type: 'fringe' },
      { word: 'yes', from: 'Lesson 30', type: 'core' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  },

  {
    number: 34,
    phoneme: '/z/',
    grapheme: 'z',
    newWords: [
      { word: 'Quin', type: 'fringe' },
      { word: 'quit', type: 'fringe' },
      { word: 'quiz', type: 'fringe' },
      { word: 'tap', type: 'fringe' },
      { word: 'taps', type: 'fringe' },
      { word: 'tin', type: 'fringe' },
      { word: 'tip', type: 'fringe' },
      { word: 'Zak', type: 'fringe' },
      { word: 'zap', type: 'fringe' },
      { word: 'zaps', type: 'fringe' },
      { word: 'zip', type: 'fringe' },
      { word: 'zips', type: 'fringe' },
      { word: 'zit', type: 'fringe' },
      { word: 'zits', type: 'fringe' },
    ],
    reviewWords: [
      { word: 'ed', from: 'Lesson 33', type: 'fringe' },
      { word: 'end', from: 'Lesson 33', type: 'fringe' },
      { word: 'ex', from: 'Lesson 33', type: 'fringe' },
      { word: 'fan', from: 'Lesson 11', type: 'fringe' },
      { word: 'fax', from: 'Lesson 31', type: 'fringe' },
      { word: 'Quin', from: 'Lesson 34', type: 'fringe' },
      { word: 'quit', from: 'Lesson 32', type: 'fringe' },
      { word: 'quiz', from: 'Lesson 34', type: 'fringe' },
      { word: 'tap', from: 'Lesson 6', type: 'fringe' },
      { word: 'taps', from: 'Lesson 20', type: 'fringe' },
      { word: 'tin', from: 'Lesson 9', type: 'fringe' },
      { word: 'tip', from: 'Lesson 8', type: 'fringe' },
      { word: 'van', from: 'Lesson 33', type: 'fringe' },
      { word: 'vast', from: 'Lesson 33', type: 'fringe' },
      { word: 'vat', from: 'Lesson 33', type: 'fringe' },
      { word: 'vax', from: 'Lesson 33', type: 'fringe' },
      { word: 'vend', from: 'Lesson 33', type: 'fringe' },
      { word: 'vent', from: 'Lesson 33', type: 'fringe' },
      { word: 'vest', from: 'Lesson 33', type: 'fringe' },
      { word: 'vet', from: 'Lesson 33', type: 'fringe' },
      { word: 'vex', from: 'Lesson 33', type: 'fringe' },
      { word: 'wax', from: 'Lesson 31', type: 'fringe' },
      { word: 'Zak', from: 'Lesson 34', type: 'fringe' },
      { word: 'zap', from: 'Lesson 34', type: 'fringe' },
      { word: 'zaps', from: 'Lesson 34', type: 'fringe' },
      { word: 'zip', from: 'Lesson 34', type: 'fringe' },
      { word: 'zips', from: 'Lesson 34', type: 'fringe' },
      { word: 'zit', from: 'Lesson 34', type: 'fringe' },
      { word: 'zits', from: 'Lesson 34', type: 'fringe' },
    ],
    heartWords: [],
    morphologyNotes: [
    ],
  }

];

module.exports = lessons;

