/**
 * Nonfiction Unit Vocabulary Configs — Communicate by Design
 *
 * Core and fringe words for each nonfiction/fiction unit,
 * extracted from the unit drafts. Used by build_unit_printable_kit.js
 * to generate symbol cards, word cards, communication boards, etc.
 *
 * Format matches UFLI lesson config shape so the same kit builder works.
 */

const units = [

  // ──────────────────────────────────────────────────────────
  // RADIUM GIRLS — LIVE on TPT
  // 27 core + 17 fringe = 44 words
  // ──────────────────────────────────────────────────────────
  {
    number: 1,
    unitTitle: 'Radium Girls',
    productLine: 'Nonfiction Reading Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (27)
      { word: 'think', type: 'core' },
      { word: 'feel', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'good', type: 'core' },
      { word: 'bad', type: 'core' },
      { word: 'right', type: 'core' },
      { word: 'wrong', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'why', type: 'core' },
      { word: 'help', type: 'core' },
      { word: 'stop', type: 'core' },
      { word: 'fight', type: 'core' },
      { word: 'change', type: 'core' },
      { word: 'same', type: 'core' },
      { word: 'different', type: 'core' },
      { word: 'more', type: 'core' },
      { word: 'less', type: 'core' },
      { word: 'before', type: 'core' },
      { word: 'after', type: 'core' },
      { word: 'true', type: 'core' },
      { word: 'false', type: 'core' },
      { word: 'show', type: 'core' },
      { word: 'mean', type: 'core' },
      { word: 'prove', type: 'core' },
      { word: 'first', type: 'core' },
      { word: 'then', type: 'core' },
      { word: 'last', type: 'core' },
      // Fringe words (17)
      { word: 'radium', type: 'fringe' },
      { word: 'factory', type: 'fringe' },
      { word: 'worker', type: 'fringe' },
      { word: 'paint', type: 'fringe' },
      { word: 'sick', type: 'fringe' },
      { word: 'law', type: 'fringe' },
      { word: 'court', type: 'fringe' },
      { word: 'safe', type: 'fringe' },
      { word: 'danger', type: 'fringe' },
      { word: 'company', type: 'fringe' },
      { word: 'money', type: 'fringe' },
      { word: 'protect', type: 'fringe' },
      { word: 'today', type: 'fringe' },
      { word: 'bone', type: 'fringe' },
      { word: 'doctor', type: 'fringe' },
      { word: 'lie', type: 'fringe' },
      { word: 'proof', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

  // ──────────────────────────────────────────────────────────
  // KEIKO: A WHALE'S JOURNEY — LIVE on TPT
  // 28 core + 22 fringe = 50 words
  // ──────────────────────────────────────────────────────────
  {
    number: 2,
    unitTitle: 'Keiko: A Whale\'s Journey',
    productLine: 'Nonfiction Reading Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (28)
      { word: 'think', type: 'core' },
      { word: 'feel', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'good', type: 'core' },
      { word: 'bad', type: 'core' },
      { word: 'best', type: 'core' },
      { word: 'free', type: 'core' },
      { word: 'live', type: 'core' },
      { word: 'place', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'why', type: 'core' },
      { word: 'help', type: 'core' },
      { word: 'care', type: 'core' },
      { word: 'same', type: 'core' },
      { word: 'different', type: 'core' },
      { word: 'more', type: 'core' },
      { word: 'less', type: 'core' },
      { word: 'before', type: 'core' },
      { word: 'after', type: 'core' },
      { word: 'true', type: 'core' },
      { word: 'false', type: 'core' },
      { word: 'show', type: 'core' },
      { word: 'mean', type: 'core' },
      { word: 'prove', type: 'core' },
      { word: 'first', type: 'core' },
      { word: 'then', type: 'core' },
      { word: 'last', type: 'core' },
      { word: 'which', type: 'core' },
      // Fringe words (22)
      { word: 'captivity', type: 'fringe' },
      { word: 'ocean', type: 'fringe' },
      { word: 'whale', type: 'fringe' },
      { word: 'park', type: 'fringe' },
      { word: 'sick', type: 'fringe' },
      { word: 'healthy', type: 'fringe' },
      { word: 'home', type: 'fringe' },
      { word: 'family', type: 'fringe' },
      { word: 'pod', type: 'fringe' },
      { word: 'human', type: 'fringe' },
      { word: 'wild', type: 'fringe' },
      { word: 'move', type: 'fringe' },
      { word: 'swim', type: 'fringe' },
      { word: 'learn', type: 'fringe' },
      { word: 'die', type: 'fringe' },
      { word: 'freedom', type: 'fringe' },
      { word: 'safe', type: 'fringe' },
      { word: 'danger', type: 'fringe' },
      { word: 'company', type: 'fringe' },
      { word: 'protect', type: 'fringe' },
      { word: 'today', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

  // ──────────────────────────────────────────────────────────
  // FRANCES KELSEY / THALIDOMIDE — BUILT, not yet LIVE
  // 27 core + 17 fringe = 44 words
  // ──────────────────────────────────────────────────────────
  {
    number: 3,
    unitTitle: 'Frances Kelsey and the Thalidomide Crisis',
    productLine: 'Nonfiction Reading Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (27)
      { word: 'say', type: 'core' },
      { word: 'think', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'want', type: 'core' },
      { word: 'not', type: 'core' },
      { word: 'good', type: 'core' },
      { word: 'bad', type: 'core' },
      { word: 'wrong', type: 'core' },
      { word: 'right', type: 'core' },
      { word: 'help', type: 'core' },
      { word: 'stop', type: 'core' },
      { word: 'go', type: 'core' },
      { word: 'more', type: 'core' },
      { word: 'different', type: 'core' },
      { word: 'same', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'but', type: 'core' },
      { word: 'if', type: 'core' },
      { word: 'true', type: 'core' },
      { word: 'question', type: 'core' },
      { word: 'answer', type: 'core' },
      { word: 'prove', type: 'core' },
      { word: 'show', type: 'core' },
      { word: 'tell', type: 'core' },
      { word: 'believe', type: 'core' },
      { word: 'strong', type: 'core' },
      { word: 'weak', type: 'core' },
      // Fringe words (17)
      { word: 'FDA', type: 'fringe' },
      { word: 'drug', type: 'fringe' },
      { word: 'safe', type: 'fringe' },
      { word: 'test', type: 'fringe' },
      { word: 'approve', type: 'fringe' },
      { word: 'deny', type: 'fringe' },
      { word: 'claim', type: 'fringe' },
      { word: 'evidence', type: 'fringe' },
      { word: 'reasoning', type: 'fringe' },
      { word: 'thalidomide', type: 'fringe' },
      { word: 'birth defect', type: 'fringe' },
      { word: 'company', type: 'fringe' },
      { word: 'pressure', type: 'fringe' },
      { word: 'review', type: 'fringe' },
      { word: 'scientist', type: 'fringe' },
      { word: 'law', type: 'fringe' },
      { word: 'protect', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

  // ──────────────────────────────────────────────────────────
  // 504 SIT-IN 1977 — BUILT, not yet LIVE
  // 26 core + 19 fringe = 45 words
  // ──────────────────────────────────────────────────────────
  {
    number: 4,
    unitTitle: '504 Sit-In 1977',
    productLine: 'Nonfiction Reading Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (26) — organized by category from draft
      { word: 'different', type: 'core' },
      { word: 'same', type: 'core' },
      { word: 'good', type: 'core' },
      { word: 'bad', type: 'core' },
      { word: 'big', type: 'core' },
      { word: 'more', type: 'core' },
      { word: 'not', type: 'core' },
      { word: 'think', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'want', type: 'core' },
      { word: 'feel', type: 'core' },
      { word: 'like', type: 'core' },
      { word: 'help', type: 'core' },
      { word: 'say', type: 'core' },
      { word: 'tell', type: 'core' },
      { word: 'do', type: 'core' },
      { word: 'make', type: 'core' },
      { word: 'go', type: 'core' },
      { word: 'get', type: 'core' },
      { word: 'stop', type: 'core' },
      { word: 'give', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'but', type: 'core' },
      { word: 'and', type: 'core' },
      { word: 'about', type: 'core' },
      { word: 'that', type: 'core' },
      // Fringe words (19) — organized by category from draft
      { word: 'Califano', type: 'fringe' },
      { word: 'Heumann', type: 'fringe' },
      { word: 'protesters', type: 'fringe' },
      { word: 'government', type: 'fringe' },
      { word: 'media', type: 'fringe' },
      { word: 'activist', type: 'fringe' },
      { word: 'disability', type: 'fringe' },
      { word: 'rights', type: 'fringe' },
      { word: 'regulations', type: 'fringe' },
      { word: 'accessible', type: 'fringe' },
      { word: 'coalition', type: 'fringe' },
      { word: 'perspective', type: 'fringe' },
      { word: 'sit-in', type: 'fringe' },
      { word: 'framing', type: 'fringe' },
      { word: 'purpose', type: 'fringe' },
      { word: 'victory', type: 'fringe' },
      { word: 'occupy', type: 'fringe' },
      { word: 'demand', type: 'fringe' },
      { word: 'sign', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

  // ──────────────────────────────────────────────────────────
  // CAPITOL CRAWL 1990 — BUILT, not yet LIVE
  // 19 core + 14 fringe = 33 words
  // ──────────────────────────────────────────────────────────
  {
    number: 5,
    unitTitle: 'Capitol Crawl 1990',
    productLine: 'Nonfiction Reading Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (19)
      { word: 'think', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'true', type: 'core' },
      { word: 'false', type: 'core' },
      { word: 'same', type: 'core' },
      { word: 'different', type: 'core' },
      { word: 'good', type: 'core' },
      { word: 'bad', type: 'core' },
      { word: 'strong', type: 'core' },
      { word: 'weak', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'but', type: 'core' },
      { word: 'agree', type: 'core' },
      { word: 'disagree', type: 'core' },
      { word: 'why', type: 'core' },
      { word: 'who', type: 'core' },
      { word: 'what', type: 'core' },
      { word: 'where', type: 'core' },
      { word: 'when', type: 'core' },
      // Fringe words (14)
      { word: 'crawl', type: 'fringe' },
      { word: 'Capitol', type: 'fringe' },
      { word: 'steps', type: 'fringe' },
      { word: 'protest', type: 'fringe' },
      { word: 'law', type: 'fringe' },
      { word: 'ADA', type: 'fringe' },
      { word: 'ADAPT', type: 'fringe' },
      { word: 'source', type: 'fringe' },
      { word: 'reliable', type: 'fringe' },
      { word: 'corroborate', type: 'fringe' },
      { word: 'evidence', type: 'fringe' },
      { word: 'claim', type: 'fringe' },
      { word: 'verify', type: 'fringe' },
      { word: 'contradict', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

  // ──────────────────────────────────────────────────────────
  // ZITKALA-ŠA — BUILT, not yet LIVE
  // 20 core + 8 fringe = 28 words
  // ──────────────────────────────────────────────────────────
  {
    number: 6,
    unitTitle: 'Zitkala-Ša',
    productLine: 'Nonfiction Reading Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (20)
      { word: 'think', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'feel', type: 'core' },
      { word: 'why', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'but', type: 'core' },
      { word: 'and', type: 'core' },
      { word: 'same', type: 'core' },
      { word: 'different', type: 'core' },
      { word: 'change', type: 'core' },
      { word: 'make', type: 'core' },
      { word: 'do', type: 'core' },
      { word: 'help', type: 'core' },
      { word: 'stop', type: 'core' },
      { word: 'want', type: 'core' },
      { word: 'need', type: 'core' },
      { word: 'right', type: 'core' },
      { word: 'wrong', type: 'core' },
      { word: 'good', type: 'core' },
      { word: 'bad', type: 'core' },
      // Fringe words (8 + 4 structural terms = 12)
      { word: 'boarding school', type: 'fringe' },
      { word: 'assimilation', type: 'fringe' },
      { word: 'reservation', type: 'fringe' },
      { word: 'testimony', type: 'fringe' },
      { word: 'organize', type: 'fringe' },
      { word: 'cause', type: 'fringe' },
      { word: 'effect', type: 'fringe' },
      { word: 'problem', type: 'fringe' },
      { word: 'solution', type: 'fringe' },
      { word: 'structure', type: 'fringe' },
      { word: 'identity', type: 'fringe' },
      { word: 'culture', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

  // ──────────────────────────────────────────────────────────
  // WONDER: CHARACTER ANALYSIS — Fiction Anchor Text Unit #1
  // RL.6.3 / RL.7.3 | Grades 3–8
  // 12 core + 12 fringe = 24 words
  // ──────────────────────────────────────────────────────────
  {
    number: 7,
    unitTitle: 'Wonder: Character Analysis',
    productLine: 'Fiction Anchor Text Unit',
    phoneme: '',
    grapheme: '',
    newWords: [
      // Core words (12) — emotional/cognitive vocabulary for character analysis
      { word: 'feel', type: 'core' },
      { word: 'want', type: 'core' },
      { word: 'think', type: 'core' },
      { word: 'know', type: 'core' },
      { word: 'change', type: 'core' },
      { word: 'because', type: 'core' },
      { word: 'maybe', type: 'core' },
      { word: 'sad', type: 'core' },
      { word: 'scared', type: 'core' },
      { word: 'happy', type: 'core' },
      { word: 'alone', type: 'core' },
      { word: 'kind', type: 'core' },
      // Fringe words (12) — character/narrative vocabulary specific to Wonder
      { word: 'different', type: 'fringe' },
      { word: 'belong', type: 'fringe' },
      { word: 'invisible', type: 'fringe' },
      { word: 'brave', type: 'fringe' },
      { word: 'loyal', type: 'fringe' },
      { word: 'bully', type: 'fringe' },
      { word: 'ordinary', type: 'fringe' },
      { word: 'friend', type: 'fringe' },
      { word: 'helmet', type: 'fringe' },
      { word: 'school', type: 'fringe' },
      { word: 'choose', type: 'fringe' },
      { word: 'face looks different', type: 'fringe' },
    ],
    reviewWords: [],
    heartWords: [],
    morphologyNotes: [],
  },

];

module.exports = units;
